# From https://github.com/chanshiyucx/chanshiyucx/blob/main/.github/workflows/metrics.yml
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Blog Github Stats
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-calendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Readme General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: general.svg
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, discussions, topics
          plugin_isocalendar: yes
          plugin_languages: yes
          # plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 10
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_discussions: yes
